### ISSUE TITLE
How to obtain the the supplementary?

### ISSUE THREAD

**Issue by yangjiangeyjg** [vhvkhoa/TAPG-AgentEnvInteration#3]
How to obtain the supplementary? @vhvkhoa 
Thanks!

**Comment by vhvkhoa** [comment]
Thank you for asking, I am attaching the supplementary here.
[AEI_supp.pdf](https://github.com/vhvkhoa/TAPG-AgentEnvInteration/files/7561197/AEI_supp.pdf)
